# This is a basic workflow to help you get started with Actions

name: Generating AutoDocs.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  generate_autodocs_job:
    runs-on: ubuntu-latest
    name: Generates automatic documentation for express APIs
    steps:
    - name: Reading the file
      id: reading-file
      uses: Pika1998/express-autodocs@v0.0.0-beta.4
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.reading-file.outputs.time }}"
